version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "America/Chicago"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    assignees:
      - "ervwalter"
    commit-message:
      prefix: "deps"
    cooldown:
      default-days: 5
    groups:
      pip-minor-and-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
      pip-major:
        patterns: ["*"]
        update-types: ["major"]
